trigger: none

pool:
  vmImage: 'windows-latest'

variables:
- group: DL-Secrets

steps:
- task: DownloadSecureFile@1
  name: fetchCert
  inputs:
    secureFile: 'DLTrackingCert.pfx'

- powershell: |
    $cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2
    $cert.Import("$(fetchCert.secureFilePath)", "$(PFX_PASSWORD)", "PersistKeySet")
    $thumbprint = $cert.Thumbprint

    Write-Host "Using cert thumbprint: $thumbprint"

- powershell: |
    $cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2
    $cert.Import("$(fetchCert.secureFilePath)", "$(PFX_PASSWORD)", "PersistKeySet")
    $thumbprint = $cert.Thumbprint

    Write-Host "Using cert thumbprint: $thumbprint"

    & "$(Build.SourcesDirectory)/Groups/DLchanges.ps1" `
        -appId "$(APP_ID)" `
        -orgName "$(ORG_DOMAIN)" `
        -thumbprint $thumbprint `
        -previous "$(DL_HISTORY_FILE)" `
        -report "$(DL_REPORT_FILE)"
  displayName: Run DL Tracking Script

- publish: '$(DL_REPORT_FILE)'
  artifact: DLReport
  displayName: Publish DL Report