trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  snapshotFileName: "snapshot_latest.json"

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'

- script: |
    python -m pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    artifactName: 'snapshots'
    downloadPath: '$(Pipeline.Workspace)/downloaded'
  continueOnError: true
  displayName: 'Download previous snapshot artifact'

- script: |
    cp $(Pipeline.Workspace)/downloaded/snapshot_latest.json snapshot_latest.json || echo "No previous snapshot found. Starting fresh."
    python your_script.py
  displayName: 'Run snapshot script'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '.'
    ArtifactName: 'snapshots'
    publishLocation: 'Container'
  displayName: 'Publish new snapshot artifact'
