trigger: none

pool:
  vmImage: 'windows-latest'

variables:
- group: DL-Secrets

steps:
- checkout: self

# ✅ Try to download previous DL state (if available)
- task: DownloadPipelineArtifact@2
  displayName: Download Previous DL State
  continueOnError: true
  inputs:
    buildType: 'current'
    artifactName: 'DLReport'
    targetPath: 'prev'

# ✅ Load certificate
- task: DownloadSecureFile@1
  name: fetchCert
  inputs:
    secureFile: 'DLTrackingCert.pfx'

# ✅ Debug script file discovery (optional)
- task: PowerShell@2
  displayName: Debug - List all .ps1 files
  inputs:
    targetType: inline
    script: |
      Write-Host "Listing all .ps1 files:"
      Get-ChildItem -Path "$(Build.SourcesDirectory)" -Recurse -Filter *.ps1

# ✅ Run DL Tracking Script
- task: PowerShell@2
  displayName: Run DL Tracking Script
  inputs:
    targetType: inline
    script: |
      # Load cert
      $cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2
      $cert.Import("$(fetchCert.secureFilePath)", "$(PFX_PASSWORD)", "PersistKeySet")
      $thumbprint = $cert.Thumbprint

      # Ensure previous state file exists (initialize on first run)
      $prevFile = "$(Build.SourcesDirectory)/prev/$(DL_HISTORY_FILE)"
      if (-not (Test-Path $prevFile)) {
        Write-Host "No previous state found. Creating an empty baseline JSON file."
        '{}' | Out-File $prevFile -Encoding utf8
      }

      # Run script
      & "$(Build.SourcesDirectory)/Distribution_lists/DLchanges.ps1" `
        -appId "$(APP_ID)" `
        -orgName "$(ORG_DOMAIN)" `
        -thumbprint $thumbprint `
        -previous $prevFile `
        -report "$(DL_REPORT_FILE)"

# ✅ Collect output and publish artifacts
- task: PowerShell@2
  displayName: Move output files to folder
  inputs:
    targetType: inline
    script: |
      mkdir output
      Move-Item "$(DL_REPORT_FILE)" output/ -Force
      Move-Item "$(Build.SourcesDirectory)/prev/$(DL_HISTORY_FILE)" output/ -Force

- publish: 'output'
  artifact: DLReport
  displayName: Publish Report + State Files
