trigger: none  # Manual or scheduled trigger only

variables:
- group: 'Critical-Group-Vars' # Variable group containing sensitive info
- name: inputPath
  value: 'inputs/critical_groups.csv'

pool:
  vmImage: 'windows-latest'

stages:
- stage: 'GenerateCriticalGroupReport'
  displayName: 'Generate Critical Group Report'
  jobs:
  - job: 'GroupReport'
    displayName: 'Fetch and load groups from csv'
    steps:

    # Step 1: Install Python dependencies
    - script: |
        pip install -r $(Build.SourcesDirectory)/IK_Test/requirements.txt
      displayName: 'Install Python packages'

    # Step 2: Install wkhtmltopdf using Chocolatey
    - powershell: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        choco install wkhtmltopdf -y
        wkhtmltopdf --version
      displayName: 'Install wkhtmltopdf using choco'

     # Step 3: Try to download previous snapshot (if any)
    - task: DownloadPipelineArtifact@2
      displayName: 'Download previous snapshot (non-blocking)'
      continueOnError: true
      inputs:
        artifact: 'group-report-artifacts'
        path: '$(Pipeline.Workspace)/group-report-artifacts'
        source: 'specific'
        project: '$(System.TeamProject)'
        pipeline: 15
        runVersion: 'latest'

    # Step 4: Run the main script to generate the report
    - script: |
        python $(Build.SourcesDirectory)/IK_Test/Critical_group_report.py
      displayName: 'Run Group Report Script'
      env:
        TENANT_ID: $(TENANT_ID)
        CLIENT_ID: $(CLIENT_ID)
        CLIENT_SECRET: $(CLIENT_SECRET)
        GROUPS_FILTER: $(GROUPS_FILTER)
        BUILD_ARTIFACTSTAGINGDIRECTORY: $(Build.ArtifactStagingDirectory)
        PIPELINE_WORKSPACE: $(Pipeline.Workspace)

    # Step 5: Publish all artifacts (snapshot, comparison result, PDF)
    - task: PublishPipelineArtifact@1
      displayName: 'Publish group report artifacts'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'group-report-artifacts'
        publishLocation: 'pipeline'
      condition: always()
